[package]
name = "rustload"
version = "0.1.0"
authors = ["Arunanshu Biswas <mydellpc07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = ">=0.4.14"
structopt = ">=0.3.21"
clap = ">=2.33.3"
anyhow = ">=1.0.41"
confy = ">=0.4.0"
log4rs = ">=1.0.0"
serde = { version = ">=1.0.126", features = ["derive"] }
daemonize = ">=0.4.1"
signal-hook = ">=0.3.9"
lazy_static = ">=1.4.0"
terminal_size = ">=0.1.17"
ordered-float = { version = ">=2.7.0", features = ["serde"] }
strum_macros = ">=0.21.1"
indoc = ">=1.0.3"
url = ">=2.2.2"

[profile.release]
lto = "yes"
